# Generated by Django 5.0.7 on 2024-07-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_questions_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Configurations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_question", models.IntegerField(default=0)),
                ("duree", models.IntegerField(default=0)),
                ("difficulte", models.CharField(default="facile", max_length=50)),
            ],
        ),
    ]
