# Generated by Django 5.0.1 on 2024-07-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_configurations"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipe",
            name="token",
            field=models.CharField(default="the shark", max_length=255),
            preserve_default=False,
        ),
    ]
