# Generated by Django 5.0.1 on 2024-07-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_equipe_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipe",
            name="score",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="equipe",
            name="status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
