# Generated by Django 5.0.1 on 2024-07-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_equipe_score_equipe_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipe",
            name="debut_training",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="equipe",
            name="training",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="equipe",
            name="training_count",
            field=models.IntegerField(default=0),
        ),
    ]
