# Generated by Django 5.0.1 on 2024-07-20 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_equipe_debut_training_equipe_training_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipe",
            name="debut_training",
        ),
        migrations.RemoveField(
            model_name="equipe",
            name="score",
        ),
        migrations.RemoveField(
            model_name="equipe",
            name="training",
        ),
        migrations.RemoveField(
            model_name="equipe",
            name="training_count",
        ),
        migrations.CreateModel(
            name="Trainings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "equipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.equipe"
                    ),
                ),
            ],
        ),
    ]
